// ============================================
// NeuralMint — Curated Prompt Vault Data
// ============================================

import type { PromptVaultItem } from "./types";

export const PROMPT_VAULT: PromptVaultItem[] = [
  {
    id: "vault-001",
    title: "Celestial Guardian",
    description: "An ethereal guardian entity watching over a cosmic landscape with crystalline armor.",
    prompt: "An ethereal celestial guardian made of starlight and cosmic dust, floating above a nebula landscape, intricate crystalline armor reflecting prismatic light, bioluminescent wings with fractal patterns, dramatic volumetric god rays piercing through cosmic clouds, ultra-detailed, 8K resolution, cinematic composition, art by Greg Rutkowski and Alphonse Mucha, digital painting masterpiece",
    category: "Fantasy",
    difficulty: "advanced",
    promptScore: 97,
    promptTier: "legendary",
    exampleImageUrl: "https://picsum.photos/seed/vault1/600/600",
    aiModel: "dall-e-3",
    usageCount: 342,
    tags: ["celestial", "guardian", "cosmic", "ethereal", "fantasy"],
  },
  {
    id: "vault-002",
    title: "Quantum Dreamscape",
    description: "A surreal quantum physics visualization merging science and art.",
    prompt: "A quantum dreamscape where reality fractures into parallel dimensions, Schrödinger's cat simultaneously alive and dead as holographic probability waves, crystalline structures made of entangled particles, deep space void with collapsing wave functions visualized as aurora-like phenomena, subsurface scattering, octane render, hyperrealistic, art by Beksinski, 8K masterpiece, surrealist",
    category: "Abstract",
    difficulty: "master",
    promptScore: 96,
    promptTier: "legendary",
    exampleImageUrl: "https://picsum.photos/seed/vault2/600/600",
    aiModel: "dall-e-3",
    usageCount: 289,
    tags: ["quantum", "surreal", "science", "abstract", "dimensions"],
  },
  {
    id: "vault-003",
    title: "Cyberpunk Ronin",
    description: "A masterless samurai in a neon-drenched futuristic Tokyo.",
    prompt: "A cyberpunk ronin warrior standing in a rain-soaked Tokyo alley at midnight, katana blade glowing with plasma energy, holographic kanji floating around the sword, neon signs reflecting on wet pavement, cherry blossoms dissolving into data particles, volumetric fog, cinematic lighting with rim light, cyberpunk aesthetic, ultra-detailed, dramatic composition, art by Makoto Shinkai and Masamune Shirow",
    category: "Art",
    difficulty: "advanced",
    promptScore: 95,
    promptTier: "legendary",
    exampleImageUrl: "https://picsum.photos/seed/vault3/600/600",
    aiModel: "dall-e-3",
    usageCount: 567,
    tags: ["cyberpunk", "samurai", "neon", "tokyo", "futuristic"],
  },
  {
    id: "vault-004",
    title: "Bio-Mechanical Phoenix",
    description: "A phoenix reborn from mechanical and organic fusion.",
    prompt: "A bio-mechanical phoenix rising from molten circuitry, wings made of interlocking gears and living flame, body morphing between organic muscle tissue and polished chrome, sparks and embers transforming into binary code, dramatic backlit composition, volumetric lighting, concept art, art by H.R. Giger and Simon Stålenhag, 8K ultra-detailed, dark fantasy",
    category: "Sci-Fi",
    difficulty: "advanced",
    promptScore: 93,
    promptTier: "epic",
    exampleImageUrl: "https://picsum.photos/seed/vault4/600/600",
    aiModel: "dall-e-3",
    usageCount: 423,
    tags: ["phoenix", "biomechanical", "rebirth", "dark", "fusion"],
  },
  {
    id: "vault-005",
    title: "Solarpunk Oasis",
    description: "A utopian solarpunk city harmonizing technology and nature.",
    prompt: "A solarpunk oasis city built into a living canyon, buildings covered in vertical gardens and solar panels shaped like leaves, crystal-clear waterfall powering hydro generators, flying vehicles shaped like dragonflies, warm golden hour lighting, children playing near bioluminescent fountains, utopian atmosphere, wide angle aerial view, concept art, highly detailed, art by Studio Ghibli, 4K",
    category: "Fantasy",
    difficulty: "intermediate",
    promptScore: 88,
    promptTier: "epic",
    exampleImageUrl: "https://picsum.photos/seed/vault5/600/600",
    aiModel: "dall-e-3",
    usageCount: 198,
    tags: ["solarpunk", "utopia", "nature", "city", "green"],
  },
  {
    id: "vault-006",
    title: "Deep Ocean Oracle",
    description: "An ancient oracle dwelling in the abyssal depths.",
    prompt: "An ancient oracle entity dwelling in the deepest ocean trench, body made of bioluminescent coral and ancient stone, surrounded by abyssal creatures with glowing patterns, underwater god rays filtering through miles of water, volumetric caustics, ethereal and mysterious atmosphere, digital painting, art by James Jean, ultra-detailed, moody blue palette",
    category: "Fantasy",
    difficulty: "advanced",
    promptScore: 90,
    promptTier: "epic",
    exampleImageUrl: "https://picsum.photos/seed/vault6/600/600",
    aiModel: "dall-e-3",
    usageCount: 156,
    tags: ["ocean", "deep", "oracle", "bioluminescent", "mystical"],
  },
  {
    id: "vault-007",
    title: "Neon Geisha",
    description: "A futuristic geisha with holographic elements in neo-Tokyo.",
    prompt: "A futuristic geisha with holographic makeup and neon-wire kimono patterns, standing in a steaming ramen shop with floating holographic menu, rain visible through the window, warm interior vs cold neon exterior, cyberpunk meets traditional Japanese aesthetic, portrait shot, cinematic lighting, ultra-detailed, art by Artgerm and WLOP",
    category: "Portrait",
    difficulty: "intermediate",
    promptScore: 87,
    promptTier: "epic",
    exampleImageUrl: "https://picsum.photos/seed/vault7/600/600",
    aiModel: "dall-e-3",
    usageCount: 312,
    tags: ["geisha", "cyberpunk", "neon", "portrait", "japanese"],
  },
  {
    id: "vault-008",
    title: "Fractal Forest",
    description: "A mathematically perfect forest where trees grow in fractal patterns.",
    prompt: "A mystical forest where trees grow in perfect fractal patterns, Mandelbrot branches with iridescent leaves, golden ratio spirals in flower arrangements, soft morning mist, warm tones with cool shadows, fantasy botanical illustration, dreamy ethereal atmosphere, digital painting, highly detailed",
    category: "Nature",
    difficulty: "intermediate",
    promptScore: 79,
    promptTier: "rare",
    exampleImageUrl: "https://picsum.photos/seed/vault8/600/600",
    aiModel: "stable-diffusion",
    usageCount: 234,
    tags: ["fractal", "forest", "nature", "mathematical", "mystical"],
  },
  {
    id: "vault-009",
    title: "Retro Space Explorer",
    description: "A vintage space exploration scene with 1960s retrofuturism aesthetic.",
    prompt: "A retro space explorer in a 1960s-style spacesuit standing on an alien planet, vintage sci-fi aesthetic, bulky chrome helmet with round visor, alien flora with psychedelic colors, two moons in a gradient sunset sky, film grain texture, warm analog color palette, retro futurism, concept art, illustration style",
    category: "Sci-Fi",
    difficulty: "beginner",
    promptScore: 74,
    promptTier: "rare",
    exampleImageUrl: "https://picsum.photos/seed/vault9/600/600",
    aiModel: "stable-diffusion",
    usageCount: 145,
    tags: ["retro", "space", "vintage", "explorer", "alien"],
  },
  {
    id: "vault-010",
    title: "Abstract Emotions",
    description: "Pure emotion visualized as flowing abstract forms.",
    prompt: "Abstract visualization of human emotions as flowing liquid forms, joy as golden spirals merging with sorrow as deep blue waves, anger as crimson shards dissolving into serenity's green mist, minimalist composition, monochrome background with vivid color bursts, contemporary art, digital painting, emotional and expressive",
    category: "Abstract",
    difficulty: "intermediate",
    promptScore: 76,
    promptTier: "rare",
    exampleImageUrl: "https://picsum.photos/seed/vault10/600/600",
    aiModel: "dall-e-3",
    usageCount: 178,
    tags: ["abstract", "emotion", "flowing", "colorful", "contemporary"],
  },
  {
    id: "vault-011",
    title: "Steampunk Clocktower",
    description: "A massive steampunk clocktower at the heart of an industrial city.",
    prompt: "A colossal steampunk clocktower rising above a Victorian industrial city, massive brass gears visible through glass panels, steam vents releasing golden clouds, airships docking at upper platforms, warm amber lighting from gas lamps, intricate mechanical details, steampunk aesthetic, bird's eye view, concept art, highly detailed, art by Ian McQue",
    category: "Fantasy",
    difficulty: "advanced",
    promptScore: 86,
    promptTier: "epic",
    exampleImageUrl: "https://picsum.photos/seed/vault11/600/600",
    aiModel: "dall-e-3",
    usageCount: 267,
    tags: ["steampunk", "clocktower", "victorian", "industrial", "brass"],
  },
  {
    id: "vault-012",
    title: "Crystal Dragon",
    description: "A dragon made entirely of living crystal, refracting light in all directions.",
    prompt: "A majestic dragon made entirely of living crystal, body refracting rainbow light in all directions, each scale a perfect prism, flying above an obsidian mountain range, dramatic stormy sky with lightning illuminating the crystal body, caustics and light dispersion effects, fantasy art, epic composition, cinematic lighting, 8K ultra-detailed, art by Todd Lockwood and Larry Elmore",
    category: "Fantasy",
    difficulty: "advanced",
    promptScore: 91,
    promptTier: "epic",
    exampleImageUrl: "https://picsum.photos/seed/vault12/600/600",
    aiModel: "dall-e-3",
    usageCount: 389,
    tags: ["dragon", "crystal", "fantasy", "epic", "rainbow"],
  },
];
